In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [34]:
data = np.asarray([["red"], ["blue"], ["green"]]) # 고정 길이 5의 유니코드 문자열
data

array([['red'],
       ['blue'],
       ['green']], dtype='<U5')

In [35]:
encoder = OrdinalEncoder()
encoder

OrdinalEncoder()

In [36]:
result = encoder.fit_transform(data)

In [43]:
print(result)
print(result.shape)
print(type(result))

[2 0 1]
(3,)
<class 'numpy.ndarray'>

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
lencoder = LabelEncoder()
result = lencoder.fit_transform(data)

print(result)
print(result.shape)
print(type(result))

[2 0 1]
(3,)
<class 'numpy.ndarray'>

d:\anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [46]:
data = pd.read_csv("../datasets/diamonds.csv")

In [47]:
data.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [48]:
encoder = OrdinalEncoder()

In [50]:
new_data = encoder.fit_transform([data["cut"].values])
# Array 형태로 받아야 한다
# new_data = encoder.fit_transform(data["cut"].values) # Error 발생

In [51]:
from sklearn.preprocessing import OneHotEncoder

In [52]:
# OneHotEncoding
# 1. SKlearn OneHotEncoder
# 2. Pandas get_dummies

onehotencoder = OneHotEncoder(sparse_output=False)

In [54]:
onehotencoder_data = onehotencoder.fit_transform([data["color"].values])

In [55]:
onehotencoder_data

array([[1., 1., 1., ..., 1., 1., 1.]])

In [64]:
onehot_diamonds = pd.get_dummies(data, columns=["color"], sparse=False)

In [65]:
onehot_diamonds

,carat,cut,clarity,depth,table,price,x,y,z,color_D,color_E,color_F,color_G,color_H,color_I,color_J
0,0.23,Ideal,SI2,61.5,55.0,326,3.95,3.98,2.43,False,True,False,False,False,False,False
1,0.21,Premium,SI1,59.8,61.0,326,3.89,3.84,2.31,False,True,False,False,False,False,False
2,0.23,Good,VS1,56.9,65.0,327,4.05,4.07,2.31,False,True,False,False,False,False,False
3,0.29,Premium,VS2,62.4,58.0,334,4.20,4.23,2.63,False,False,False,False,False,True,False
4,0.31,Good,SI2,63.3,58.0,335,4.34,4.35,2.75,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,SI1,60.8,57.0,2757,5.75,5.76,3.50,True,False,False,False,False,False,False
53936,0.72,Good,SI1,63.1,55.0,2757,5.69,5.75,3.61,True,False,False,False,False,False,False
53937,0.70,Very Good,SI1,62.8,60.0,2757,5.66,5.68,3.56,True,False,False,False,False,False,False
53938,0.86,Premium,SI2,61.0,58.0,2757,6.15,6.12,3.74,False,False,False,False,True,False,False
53939,0.75,Ideal,SI2,62.2,55.0,2757,5.83,5.87,3.64,True,False,False,False,False,False,False

In [66]:
# Scaling
# 큰 값에 의해 작은 값이 무시될 수 있기 때문에
# 특성 간 비교하기 쉽도록 스케일을 조정해줘야 한다

# Important for Data Preperation

df = pd.read_csv("../datasets/OnlineNewsPopularity.csv")

df.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [67]:
df.describe()

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,354.530471,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,...,0.095446,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064,3395.380184
std,214.163767,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,...,0.071315,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294,11626.950749
min,8.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,1.000000
25%,164.000000,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,...,0.050000,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,946.000000
50%,339.000000,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,...,0.100000,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000,1400.000000
75%,542.000000,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,...,0.100000,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,2800.000000
max,731.000000,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,843300.000000

In [70]:
df.describe(include="object")

                                                      url
count                                               39644
unique                                              39644
top     http://mashable.com/2013/01/07/amazon-instant-...
freq                                                    1

In [71]:
# Min Max Scalier
# bar_x = (x - min(x))/(max(x)-min(x))
# 모든 값이 0와 1사이에 존재 한다

# Standard Scalier


# L2 Normalization
# Sparse Data -> L2


# TODO: 스케일러별 사용하는 케이스 다시 확인
# Skewed? 한쪽에 치우친 데이터
# Spased Data? 0이 대부분인 데이터

**MinMaxScaler:**

사용 시기: MinMaxScaler는 데이터를 고정된 범위(일반적으로 0과 1 사이)로 조정합니다. 원래 분포의 모양을 유지하고 데이터의 최소값과 최대값을 유지하려는 경우에 적합합니다. 왜곡된 데이터에 최소값과 최대값 측면에서 의미 있는 해석이 있는 경우 MinMaxScaler가 적합할 수 있습니다.

기울어진 데이터에 대한 영향: MinMaxScaler는 특히 왜곡이 극단적인 값으로 인해 발생하는 경우 이상값의 영향을 받을 수 있습니다. 치우친 분포에 이상값이 포함된 경우 MinMaxScaler는 최소값과 최대값을 기준으로 데이터 크기를 조정하여 대부분의 데이터 포인트를 범위 중심으로 압축하므로 최선의 선택이 아닐 수 있습니다.

**정규화 스케일러(StandardScaler):**

사용 시기: StandardScaler와 같은 정규화 스케일링은 평균이 0, 표준편차가 1이 되도록 데이터를 스케일링합니다. 데이터 분포를 표준화하고 평균을 제거하려는 경우에 적합합니다. 분포의 형태를 유지합니다. 치우친 데이터가 평균을 중심으로 하고 일관된 척도를 가져야 하는 경우 정규화 척도가 적절할 수 있습니다.

편향된 데이터에 미치는 영향: 정규화 스케일러는 MinMaxScaler에 비해 이상값에 덜 민감합니다. 평균 및 표준 편차를 기반으로 데이터의 규모를 조정하여 왜도가 있는 극단값에 대해 더욱 견고하게 만듭니다. 그러나 왜도가 극단적이거나 이상값이 많은 경우에는 정규화 스케일링으로 문제를 완전히 해결하지 못할 수도 있습니다.

In [72]:
# Use Min Max Scalier

In [73]:
import sklearn.preprocessing as preproc

df[" n_tokens_content"]

0         219.0
1         255.0
2         211.0
3         531.0
4        1072.0
          ...
39639     346.0
39640     328.0
39641     442.0
39642     682.0
39643     157.0
Name:  n_tokens_content, Length: 39644, dtype: float64

In [78]:
# MinMax Scalier
# Skewed
# 최소값과 최대값이 의미가 있는 경우
# 편향된 데이터를 그대로 유지

df["min_max"] = preproc.minmax_scale(df[[" n_tokens_content"]])

In [75]:
df["min_max"]

0        0.025844
1        0.030092
2        0.024900
3        0.062662
4        0.126505
           ...
39639    0.040831
39640    0.038707
39641    0.052160
39642    0.080481
39643    0.018527
Name: min_max, Length: 39644, dtype: float64

In [80]:
# Normalized data
# ??
# 평균을 제거
# 분포를 그대로 유지
# 편향된 데이터를 중심으로 옮겨야 하는 경우

df["standardized"] = preproc.StandardScaler().fit_transform(df[[" n_tokens_content"]])

In [81]:
df["standardized"]

0       -0.695210
1       -0.618794
2       -0.712192
3       -0.032933
4        1.115439
           ...
39639   -0.425630
39640   -0.463838
39641   -0.221852
39642    0.287592
39643   -0.826817
Name: standardized, Length: 39644, dtype: float64

In [82]:
# Sparsed Data
# L2
# 데이터와 훈련 세트 사이의 거리를 계산하여 예측값을 사용

df["l2_normalized"] = preproc.normalize(df[[" n_tokens_content"]], axis = 0)

In [83]:
df["l2_normalized"]

0        0.001524
1        0.001775
2        0.001469
3        0.003696
4        0.007462
           ...
39639    0.002408
39640    0.002283
39641    0.003077
39642    0.004747
39643    0.001093
Name: l2_normalized, Length: 39644, dtype: float64

In [84]:
# This is skewed data
# Example Article Word Count

In [85]:
# Prep(Scale) -> ML -> Model(Unscale)